on:
  push:
    branches:
      - temp
    tags:
      - "*"
name: Build
env:
  L4T32_BSP: 32.7.4
  L4T35_BSP: 35.5.0
  L4T36_BSP: 36.3.0
jobs:
  build:
    strategy:
      matrix:
        ubuntu: ["22.04"]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y podman qemu-user-static pigz
          sudo systemctl start systemd-binfmt.service
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Create rootfs
        run: just build-jetson-rootfs ${{ matrix.ubuntu }}

      - name: Build jetson image for Jetson nano revision 300
        if: matrix.ubuntu == '22.04'
        run: |
          just build-jetson-image  \
            -b jetson-nano \
            -r 300
          mv jetson.img "jetson-nano-300_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          pigz "jetson-nano-300_${{ matrix.ubuntu }}_${L4T32_BSP}.img"
          ls -lht "jetson-nano-300_${{ matrix.ubuntu }}_${L4T32_BSP}.img.gz"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jetson-images
          path: "jetson-nano-300_22.04_32.7.4.img.gz"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            CHANGELOG.md
          files: "jetson*"
